name: firebase_ui2
description: Firebase auth UI, dart package to mimic the firebaseUI(Google,Facebook,Twitter,Email supported)
version: 1.1.9
author: Manuel Gomes <mg@variograma.com>, Nicholas Bowler <crucifixx25@gmail.com>, Yann-Cyril Pelud <yann@fidelisa.com>
homepage: https://github.com/variograma/firebase_ui

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_twitter: ^1.1.3

  firebase_auth: ^0.16.1

  google_sign_in: ^4.1.4
  flutter_facebook_login: ^3.0.0


  apple_sign_in: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fb-logo.png
    - assets/2.0x/fb-logo.png
    - assets/3.0x/fb-logo.png

    - assets/email-logo.png
    - assets/2.0x/email-logo.png
    - assets/3.0x/email-logo.png

    - assets/go-logo.png
    - assets/2.0x/go-logo.png
    - assets/3.0x/go-logo.png

    - assets/twitter-logo.png
    - assets/2.0x/twitter-logo.png
    - assets/3.0x/twitter-logo.png
